# Generated by Django 6.1.1 on 2026-09-07 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('officer', 'Student Officer'), ('member', 'General Member'), ('adviser', 'Faculty Adviser')], default='member', max_length=10)),
                ('organization_name', models.CharField(help_text='e.g. Computer Science Society', max_length=150)),
                ('student_status', models.CharField(blank=True, help_text='e.g. 3rd Year, Alumni', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
