# Generated by Django 6.1.1 on 2026-09-08 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='organization_name',
            field=models.CharField(blank=True, default='', help_text='e.g. Computer Science Society', max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='student_status',
            field=models.CharField(blank=True, default='', help_text='e.g. 3rd Year, Alumni', max_length=100),
        ),
    ]
