# Generated by Django 6.1 on 2026-09-08 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_profile_organization_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='organization_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='student_status',
        ),
    ]
